version: '3.9'
services:
  app:
    build: .
    container_name: app
    environment:
      - PORT=80
    depends_on:
      - db
    links:
      - db
    ports:
      - 80:80
    restart: always
    volumes:
      - ./app:/app
    command: dev

  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - config/db.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
