version: '3.9'
services:
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080
    restart: always

  api:
    build: .
    container_name: api
    depends_on:
      - db
    env_file:
      - api/.env
      - db/.env
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./api:/app

  client:
    build: .
    container_name: client
    depends_on:
      - api
    environment:
      - API_PORT=3000
      - PORT=80
    ports:
      - 80:80
    restart: always
    volumes:
      - ./client:/app

  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - db/.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
